// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ARM_H
#define ARM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Arm: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> leftIntakeMotor;
	std::shared_ptr<WPI_TalonSRX> rightIntakeMotor;
	std::shared_ptr<frc::SpeedControllerGroup> intakeOuttake;
	std::shared_ptr<WPI_TalonSRX> armMotor;
	std::shared_ptr<frc::Encoder> armEncoder;
	std::shared_ptr<frc::DigitalInput> armLimitSwitchFront;
	std::shared_ptr<frc::DigitalInput> armLimitSwitchBack;
	std::shared_ptr<frc::DoubleSolenoid> armSolenoid;
	std::shared_ptr<frc::DigitalInput> armOpticalFlagSensor;
	std::shared_ptr<frc::Compressor> armCompressor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Arm();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
