// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmDump.h"
#include "Commands/ArmInitialize.h"
#include "Commands/ArmPickup.h"
#include "Commands/ArmUpright.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/TeleopTankDrive.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystickDriverRight.reset(new frc::Joystick(1));
    
    joystickDriverLeft.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Arm Dump", new ArmDump());
    frc::SmartDashboard::PutData("Arm Pickup", new ArmPickup());
    frc::SmartDashboard::PutData("Arm Upright", new ArmUpright());
    frc::SmartDashboard::PutData("Arm Initialize", new ArmInitialize());
    frc::SmartDashboard::PutData("Teleop Tank Drive", new TeleopTankDrive());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystickDriverLeft() {
   return joystickDriverLeft;
}

std::shared_ptr<frc::Joystick> OI::getJoystickDriverRight() {
   return joystickDriverRight;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
