// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmDump.h"
#include "Commands/ArmEjectPosition.h"
#include "Commands/ArmInitialize.h"
#include "Commands/ArmPickup.h"
#include "Commands/ArmSlew.h"
#include "Commands/ArmSlewNegative.h"
#include "Commands/ArmSlewPositive.h"
#include "Commands/ArmToggleDirection.h"
#include "Commands/ArmUpright.h"
#include "Commands/AutonomousBlendedMove.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/AutonomousMotionProfile.h"
#include "Commands/AutonomousVelocityProfile.h"
#include "Commands/IntakeClose.h"
#include "Commands/IntakeOpen.h"
#include "Commands/IntakeToggle.h"
#include "Commands/IntakeWhileHeld.h"
#include "Commands/NoCommand.h"
#include "Commands/OuttakeWhileHeld.h"
#include "Commands/TeleopTankDrive.h"
#include "Commands/ClimbUpWhileHeld.h"

#include "Commands/DriveTrainToggleDirection.h"
#include "Commands/ScissorToggle.h"
#include "Commands/ClimbDownWhileHeld.h"

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystickOperator.reset(new frc::Joystick(2));
    
    joystickButtonBumperRight.reset(new frc::JoystickButton(joystickOperator.get(), 6));
    joystickButtonBumperRight->WhenPressed(new IntakeOpen());
    joystickButtonBumperLeft.reset(new frc::JoystickButton(joystickOperator.get(), 5));
    joystickButtonBumperLeft->WhenPressed(new IntakeClose());
    joystickButtonY.reset(new frc::JoystickButton(joystickOperator.get(), 4));
    joystickButtonY->WhenPressed(new ArmUpright());
    joystickButtonX.reset(new frc::JoystickButton(joystickOperator.get(), 3));
    joystickButtonX->WhenPressed(new ArmEjectPosition());
    joystickButtonB.reset(new frc::JoystickButton(joystickOperator.get(), 2));
    joystickButtonB->WhileHeld(new OuttakeWhileHeld());
    joystickButtonA.reset(new frc::JoystickButton(joystickOperator.get(), 1));
    joystickButtonA->WhileHeld(new IntakeWhileHeld());
    
    joystickDriverLeft.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    leftDriverButtonLeft.reset(new JoystickButton(joystickDriverLeft.get(), 1));
    leftDriverButtonLeft->WhenPressed(new DriveTrainToggleDirection());

    joystickButtonBack.reset(new JoystickButton(joystickOperator.get(), 7));
    joystickButtonBack->WhenPressed(new ScissorToggle());
    joystickButtonStart.reset(new JoystickButton(joystickOperator.get(), 8));
    joystickButtonStart->WhileHeld(new ClimbUpWhileHeld());
    joystickButtonRightClick.reset(new JoystickButton(joystickOperator.get(), 10));
    joystickButtonRightClick->WhileHeld(new ClimbDownWhileHeld());


}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystickDriverLeft() {
   return joystickDriverLeft;
}

std::shared_ptr<frc::Joystick> OI::getJoystickOperator() {
   return joystickOperator;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
