// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::DigitalInput> RobotMap::armLimitSwitchFront;
std::shared_ptr<frc::DigitalInput> RobotMap::armLimitSwitchBack;
std::shared_ptr<frc::DigitalInput> RobotMap::armOpticalFlagSensor;
std::shared_ptr<WPI_TalonSRX> RobotMap::armTalonSRXArmMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    armLimitSwitchFront.reset(new frc::DigitalInput(0));
    lw->AddSensor("Arm", "Limit Switch Front", armLimitSwitchFront);
    
    armLimitSwitchBack.reset(new frc::DigitalInput(1));
    lw->AddSensor("Arm", "Limit Switch Back", armLimitSwitchBack);
    
    armOpticalFlagSensor.reset(new frc::DigitalInput(2));
    lw->AddSensor("Arm", "Optical Flag Sensor", armOpticalFlagSensor);
    
    armTalonSRXArmMotor.reset(new WPI_TalonSRX(0));
    
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
