// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveToSwitchScore.h"
#include "NoCommand.h"


DriveToSwitchScore::DriveToSwitchScore():
	ConditionalCommand(new NoCommand(), new NoCommand()) {
}

DriveToSwitchScore::DriveToSwitchScore(frc::Command* left, frc::Command* right):
	ConditionalCommand(left, right) {
}

bool DriveToSwitchScore::Condition(){
	std::string switchScalePositions = frc::DriverStation::GetInstance().GetGameSpecificMessage();

	return switchScalePositions[0] == 'L';
}
