
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef SCISSORTOGGLE_H
#define SCISSORTOGGLE_H


#include "ScissorControl.h"

#include "Commands/ConditionalCommand.h"

class ScissorToggle : public frc::ConditionalCommand {
public:
	ScissorToggle();

protected:
virtual bool Condition();
};

#endif
