// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "ctre/Phoenix.h"


/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> talonSRXMasterLeft;
	std::shared_ptr<WPI_TalonSRX> talonSRXMasterRight;
	std::shared_ptr<frc::DifferentialDrive> differentialDrive1;
	std::shared_ptr<WPI_TalonSRX> talonSRXSlaveLeft1;
	std::shared_ptr<WPI_TalonSRX> talonSRXSlaveLeft2;
	std::shared_ptr<WPI_TalonSRX> talonSRXSlaveRight1;
	std::shared_ptr<WPI_TalonSRX> talonSRXSlaveRight2;
	std::shared_ptr<frc::PowerDistributionPanel> powerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	void InitMotors();

public:
	DriveTrain();
	void InitDefaultCommand() override;
	void Periodic() override;
	void TankDrive(double leftSpeed, double rightSpeed);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
