// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ARM_H
#define ARM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Arm: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<DigitalInput> armOpticalFlagSensor;
	std::shared_ptr<WPI_TalonSRX> armMotor;
	std::shared_ptr<Encoder> armEncoder;
	std::shared_ptr<DigitalInput> armLimitSwitchFront;
	//std::shared_ptr<DigitalInput> limitSwitchHome;			2017 code
	//frc::DigitalInput to DigitalInput
	std::shared_ptr<DigitalInput> armLimitSwitchBack;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Arm();
	void InitDefaultCommand() override;
	void Periodic() override;
	bool readLimitSwitchFront();
	bool readLimitSwitchBack();
	int readArmEncoder();
	bool readArmOpticalFlagSensor();
	void stopArmMotor();
	void setArmMotorSpeed(double speed);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
